[package]
name = "core_plugin"
version = "0.1.0"
authors = ["Alec Deason <alec@tinycountry.com>"]
edition = "2018"

[lib]
 crate-type = ["cdylib"]

[dependencies]
plugin_api = { path = "../plugin_api" }
wasm_plugin_guest = { version = "0.1.3", default-features = false, features = ["serialize_nanoserde_json"] }
